/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvaRouteImport } from './routes/tva'
import { Route as TurnoverRouteImport } from './routes/turnover'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AgingRouteImport } from './routes/aging'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsEntityRouteImport } from './routes/settings.entity'
import { Route as ProductsNewRouteImport } from './routes/products.new'
import { Route as DocumentsNewRouteImport } from './routes/documents.new'
import { Route as DocumentsIdRouteImport } from './routes/documents.$id'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'

const TvaRoute = TvaRouteImport.update({
  id: '/tva',
  path: '/tva',
  getParentRoute: () => rootRouteImport,
} as any)
const TurnoverRoute = TurnoverRouteImport.update({
  id: '/turnover',
  path: '/turnover',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AgingRoute = AgingRouteImport.update({
  id: '/aging',
  path: '/aging',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsEntityRoute = SettingsEntityRouteImport.update({
  id: '/settings/entity',
  path: '/settings/entity',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsNewRoute = DocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aging': typeof AgingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/turnover': typeof TurnoverRoute
  '/tva': typeof TvaRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents/new': typeof DocumentsNewRoute
  '/products/new': typeof ProductsNewRoute
  '/settings/entity': typeof SettingsEntityRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/clients/': typeof ClientsIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aging': typeof AgingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/turnover': typeof TurnoverRoute
  '/tva': typeof TvaRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents/new': typeof DocumentsNewRoute
  '/products/new': typeof ProductsNewRoute
  '/settings/entity': typeof SettingsEntityRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/clients': typeof ClientsIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aging': typeof AgingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/turnover': typeof TurnoverRoute
  '/tva': typeof TvaRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents/new': typeof DocumentsNewRoute
  '/products/new': typeof ProductsNewRoute
  '/settings/entity': typeof SettingsEntityRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/clients/': typeof ClientsIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aging'
    | '/forgot-password'
    | '/journal'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/turnover'
    | '/tva'
    | '/clients/$id'
    | '/clients/new'
    | '/documents/$id'
    | '/documents/new'
    | '/products/new'
    | '/settings/entity'
    | '/settings/profile'
    | '/clients/'
    | '/documents/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aging'
    | '/forgot-password'
    | '/journal'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/turnover'
    | '/tva'
    | '/clients/$id'
    | '/clients/new'
    | '/documents/$id'
    | '/documents/new'
    | '/products/new'
    | '/settings/entity'
    | '/settings/profile'
    | '/clients'
    | '/documents'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/aging'
    | '/forgot-password'
    | '/journal'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/turnover'
    | '/tva'
    | '/clients/$id'
    | '/clients/new'
    | '/documents/$id'
    | '/documents/new'
    | '/products/new'
    | '/settings/entity'
    | '/settings/profile'
    | '/clients/'
    | '/documents/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgingRoute: typeof AgingRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TurnoverRoute: typeof TurnoverRoute
  TvaRoute: typeof TvaRoute
  ClientsIdRoute: typeof ClientsIdRoute
  ClientsNewRoute: typeof ClientsNewRoute
  DocumentsIdRoute: typeof DocumentsIdRoute
  DocumentsNewRoute: typeof DocumentsNewRoute
  ProductsNewRoute: typeof ProductsNewRoute
  SettingsEntityRoute: typeof SettingsEntityRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tva': {
      id: '/tva'
      path: '/tva'
      fullPath: '/tva'
      preLoaderRoute: typeof TvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turnover': {
      id: '/turnover'
      path: '/turnover'
      fullPath: '/turnover'
      preLoaderRoute: typeof TurnoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aging': {
      id: '/aging'
      path: '/aging'
      fullPath: '/aging'
      preLoaderRoute: typeof AgingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/entity': {
      id: '/settings/entity'
      path: '/settings/entity'
      fullPath: '/settings/entity'
      preLoaderRoute: typeof SettingsEntityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/new': {
      id: '/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/new': {
      id: '/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof DocumentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$id': {
      id: '/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgingRoute: AgingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TurnoverRoute: TurnoverRoute,
  TvaRoute: TvaRoute,
  ClientsIdRoute: ClientsIdRoute,
  ClientsNewRoute: ClientsNewRoute,
  DocumentsIdRoute: DocumentsIdRoute,
  DocumentsNewRoute: DocumentsNewRoute,
  ProductsNewRoute: ProductsNewRoute,
  SettingsEntityRoute: SettingsEntityRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
